version: "3.8" # Specify Docker Compose version (3.1+ recommended)

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID =SA;Password=Test@Bilal;Host=db;Port=5432;Database=NewsDB;Pooling=true;
    ports:
      - "8080:8080" # Map host port 8000 to container port 80
    depends_on:
      - db
    networks:
      - api-network
  db:
    image: postgres:latest # Use the official PostgreSQL image
    restart: always # Restart the container automatically if it stops
    environment:
      - POSTGRES_DB=NewsDB # Name of your database
      - POSTGRES_USER=SA # Database user
      - POSTGRES_PASSWORD=Test@Bilal # User's password
    ports:
      - "5432:5432" # Expose port 5432 for external access
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data even if the container is removed
    networks:
      - api-network

volumes:
  postgres_data:

networks:
  api-network:
    driver: bridge
